### ISSUE TITLE
Feature request: concatenating nested selectors

### ISSUE THREAD

**Issue by eudoxia0** [Shinmera/LASS#5]
So, in Sass, you can do this:

```sass
input {
  &[type=submit] {
    color: blue;
  }
}
```

which compiles to:

```css
input[type=submit] {
  color: blue;
}
```

To the best of my knowledge you can't do this with Lass. It's a useful feature since keeping the selectors nested is more semantic and makes it easier to move trees of style around.

**Comment by VyacheslavMik** [comment]
I think you can write something like this:
```lisp
(lass:compile-and-write
	'((:and input (:= type "submit"))
	  :color "blue"))
```
and you get:
```css
input[type="submit"]{
    color: blue;
}
```

**Comment by Shinmera** [comment]
That's not the same. He wants to be able to nest blocks and make them combine with the parent; something like this:
```lisp
(a
  :color black
  ((:and :parent :hover)
    :color red))
```
Resulting in
```CSS
a{color: black}
a:hover{color: red}
```
